### ISSUE TITLE
jupyterlab terminal not working in safari?

### ISSUE THREAD

**Issue by robnagler** [radiasoft/container-beamsim-jupyter-base#19]
I just logged in from safari, and launched a terminal which was "all black". Works in Firefox and Chrome.

**Comment by bruhwiler** [comment]
Just tested this on Win10/Firefox and Win10/Edge.
The terminal worked fine for these combinations.

**Comment by robnagler** [comment]
alpha is running jupyterlab-1.0.6 which doesn't seem to have this problem. Prod version was 1.0.1.

**Comment by linflxl** [comment]
Hi Rob,

The Jupyter works for me now. Thanks !

Fanglei

**Comment by linflxl** [comment]
Somehow, the "Find and Replace" in the "Edit" disappears. I do choose "emacs" as the text editor in "Settings". Does it go somewhere else or I lose this function?

Fanglei

**Comment by robnagler** [comment]
@linflxl It seems they changed the user interface. When you "find", you will see a *tiny* right arrow in the box to the left of the text you are searching for. Click that and you'll be able to replace. see https://github.com/jupyterlab/jupyterlab/issues/1074#issuecomment-501633298

**Comment by linflxl** [comment]
got it !  Thanks !
