### ISSUE TITLE
fete error finding RadiaSoft rc styles from Jupyter notebook

### ISSUE THREAD

**Issue by ncook882** [radiasoft/container-beamsim-jupyter-base#27]
On my jupyter server instance, I'm unable to load the RadiaSoft rc file. 

The matplotlib config directory is correctly listed as `/home/vagrant/.config/matplotlib`, and the appropriate style files exist.

However, the none of the "rs_" styles appear as available options from within Jupyter notebooks, and attempting to load them produces an error. The same issue occurs when running Python or IPython from the terminal.

**Comment by robnagler** [comment]
Not sure when this changed, but the files now have to live in `~/.config/matplotlib/stylelib`.

The fix will get pushed as soon as we get the new py3 environment built. This is a matter of days, hopefully.

**Comment by ncook882** [comment]
Thanks @robnagler. I should have figured this out myself. I made the changes on my server, so no rush on pushing the fix.
