### ISSUE TITLE
setuptools race condition 

### ISSUE THREAD

**Issue by elventear** [radiasoft/container-beamsim-jupyter-base#3]
The build is broken due to an unexpected error while upgrading a third party python package:

https://travis-ci.org/radiasoft/container-beamsim-jupyter/builds/205214779

The error seems to be related to:

https://github.com/pypa/setuptools/issues/951

**Comment by elventear** [comment]
This commit suggests a host of versions of setuptools that should be avoided. 

https://github.com/openstack/requirements/commit/4ef43878d1c928c9f46909c64d21759fa4066a9b#diff-d7d5c6fa7118ea10d88f3afeaef4da77R388

**Comment by robnagler** [comment]
setuptools breaks builds quite a bit. We should probably use a fixed version we know works, and avoid any others until we decide to upgrade.

**Comment by robnagler** [comment]
Something is up with tox py27 and setuptools 34.3.0. pykern build is failing when trying to force to setuptools==32.1.3.

I'll try to debug, but if anybody else has ideas...

https://travis-ci.org/radiasoft/pykern/builds/205650568#L565

**Comment by robnagler** [comment]
Fixed by forcing setuptools version to 32.1.3.
