### ISSUE TITLE
include sirepo package with jupyter

### ISSUE THREAD

**Issue by moellep** [radiasoft/container-beamsim-jupyter-base#31]
The sirepo jupyter export relies on the sirepo.analysis.ml module.

**Comment by robnagler** [comment]
radiasoft/beamsim-jupyter is based off radiasoft/sirepo. We are building sirepo regularly so we will always have a relatively up-to-date radiasoft/sirepo:latest which is what is used to build.

**Comment by robnagler** [comment]
@moellep on Monday we should build alpha sirepo then jupyter so we can test this. Just noting here, because I'll forget. :)
