### ISSUE TITLE
%matplotlib widget: Error displaying widget: model not found

### ISSUE THREAD

**Issue by cchall** [radiasoft/container-beamsim-jupyter-base#37]
The `%matplotlib widget` option seems to have recently broken on Jupyter. Trying the following just gives an error:

```
%matplotlib widget

import matplotlib.pyplot as plt

plt.figure()
plt.plot(1, 1)
plt.show()
```
> Error displaying widget: model not found

**Comment by robnagler** [comment]
@cchall this fix is on production. If you restart your server, you won't need to do the workaround. You don't have to restart, of course.
