### ISSUE TITLE
graph-tool

### ISSUE THREAD

**Issue by sjcrs** [radiasoft/container-beamsim-jupyter-base#40]
https://git.skewed.de/count0/graph-tool/-/wikis/installation-instructions#native-installation

As it describes in the writeup, it's a python package that cannot be installed with pip. It has dependencies on Boost & OpenMP, and it suggests optimization.

Thanks!

**Comment by robnagler** [comment]
https://github.com/radiasoft/download/commit/8e26f6a3b952217a060b2499990fc4eaff2fff3b created rpms

**Comment by robnagler** [comment]
`RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd`

numpy is getting upgraded during the build.

**Comment by robnagler** [comment]
It's getting downgraded during beamsim-jupyter build. This is probably why we should install all codes with rpms in all docker images so we could see this conflict.

**Comment by robnagler** [comment]
gpflow is the culprit by installing tensorflow (ignoring existing version). It's also downgrading h5py to 2.1 (from 3.2.1) and a few others (jedi, parso).
