### ISSUE TITLE
Add bluesky to beamsim-jupyter

### ISSUE THREAD

**Issue by ncook882** [radiasoft/container-beamsim-jupyter-base#42]
RayData could benefit from having this available for testing/learning purposes.

**Comment by robnagler** [comment]
@e-carlin at your convenience but within a week.

**Comment by ncook882** [comment]
I'm getting a module not found error when trying to import bluesky, which I previously did not receive.

`ModuleNotFoundError: No module named 'bluesky'`

**Comment by robnagler** [comment]
I don't think this is on production. You can pip install bluesky for now.

I think we need more stuff for the notebooks to work properly.

**Comment by ncook882** [comment]
@robnagler I'm happy to pip install for now.

We would also benefit from [scikit-beam](https://github.com/scikit-beam/scikit-beam) and [scikit-beam-examples](https://github.com/scikit-beam/scikit-beam-examples).

For context, Boaz and I will be creating some notebooks which template different analyses based upon scikit-beam examples along with the workflows presented for CHX and CSX beamlines. These notebooks will serve to help us coordinate and benchmark analysis-specific interface features in the future.
