### ISSUE TITLE
Document testing

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/container-beamsim-jupyter-base#44]
@robnagler when you have some time would you mind documenting what your cycle for making changes and testing is? I tried following the steps in container-conf/README but ran into `mkdir: cannot create directory ‘/root’: Permission denied`. Those steps also look like they push to alpha which isn't right for my testing. For sirepo I build and tag an image and then test it by deploying with rsconf in my dev env. A similar workflow here would be great if possible.

**Comment by robnagler** [comment]
Does this work https://github.com/radiasoft/container-beamsim-jupyter/blob/master/container-conf/README.md ?

**Comment by robnagler** [comment]
container-build is working for me

**Comment by e-carlin** [comment]
It worked for me after updating my radiasoft/fedora image.
