### ISSUE TITLE
explore pytorch vs tensorflow 

### ISSUE THREAD

**Issue by j-edelen** [radiasoft/container-beamsim-jupyter-base#50]
@robnagler please explore the tradeoffs of running with pytorch or tensorflow when it comes to dependencies. This is in support of webcon.

**Comment by robnagler** [comment]
@e-carlin one of the problems is numpy. Tensorflow seems to work with an upgraded version, but not always. I think @j-edelen could provide an example where the upgraded numpy fails. Then we could compare pytorch vs tensorflow.

**Comment by j-edelen** [comment]
@e-carlin, I will send you a zip file with a tensorflow example that fails due to numpy.

**Comment by robnagler** [comment]
Relevant? If so which project?

**Comment by j-edelen** [comment]
I don't even remember the original issue. Was this for jupyter or GPU jupyter?

**Comment by robnagler** [comment]
Both.

**Comment by robnagler** [comment]
We support both.
