### ISSUE TITLE
Enable Jupyter Lab on RadiaSoft Jupyter servers

### ISSUE THREAD

**Issue by ncook882** [radiasoft/container-beamsim-jupyter-base#6]
[JupyterLab](https://github.com/jupyterlab/jupyterlab) has been available a for a few months now, and I've had several recommendations from colleagues at ICAP that including this resource on our Jupyter servers may be useful for our work, as well as for educational outreach and attracting new users.

It would be great if we could include this on our Jupyter server builds.

**Comment by robnagler** [comment]
We are using jupyterlab to launch jupyter. However, we cannot use jupyterlab widgets in our Python 2 notebooks, because it is Python 3 only.

What would you like to accomplish by enabling JupyterLab?

**Comment by ncook882** [comment]
My interest is in making use of the interface niceties, such as the tabbed work area, code execution, and other IDE-like properties. Currently I find myself switching between upwards of 5-6 tabs just for prototyping some code or running a few scans on the server.

Even if it's only available for Python 3, it might be nice to support these Lab features because other users may expect them when making use of our servers. I believe that NERSC has deployed it on some of their nodes, along with other HPC centers. It could also be very helpful for USPAS or other educational platforms.

**Comment by robnagler** [comment]
@ncook882 JuptyerLab is installed, as I thought, but it is not the default URL. To get to JupyterLab, login to your JupyterHub server, and then change the end of the URL from `/tree` to `/lab`.

I'm also going to update Jupyter/Hub to the latest. We're a few versions behind so no doubt bugs have been fixed. However, the above should work fine.

If we decide the JupyterLab should be the default URL for our JupyterHub configurations, it's an easy change.

**Comment by robnagler** [comment]
Ran into some weirdness with labhub. See https://github.com/jupyterhub/jupyterhub/issues/2213#issuecomment-438856084 

I think I can hack around this, but it's a little bit of work.

**Comment by robnagler** [comment]
I figured it out in https://github.com/radiasoft/container-beamsim-jupyter/commit/55652375509d84ef14ad997c926cb69957528fc7

**Comment by robnagler** [comment]
In https://github.com/radiasoft/container-beamsim-jupyter/commit/55652375509d84ef14ad997c926cb69957528fc7 JupyterLab is the default. This will be deployed next week.

**Comment by ncook882** [comment]
Upon returning to a Jupyter lab session I received the following error:

<img width="308" alt="screen shot 2018-11-14 at 6 12 26 pm" src="https://user-images.githubusercontent.com/11053323/48523312-249f4e00-e839-11e8-8962-07f673acf9cd.png">

The standard 'tree' configuration still works, but lab is unresponsive. @robnagler, this may be related to the unique configuration being used for my server. I've yet to reproduce it on other servers.

**Comment by robnagler** [comment]
When you say "returning", what exactly do you mean? Visiting /lab in a browser window, walking away from the computer, and then coming back without refreshing or other click? I just visited /lab on your server, and it worked, but that was from a fresh browser.

**Comment by ncook882** [comment]
By "returning" I mean that my computer slept while I was away from it.

**Comment by robnagler** [comment]
I have not been able to reproduce this either with your server or the new jupyterlab stuff I'm using.

Do you have anything like "Great Suspender" or other plugins that might muck with the tab?

**Comment by cchall** [comment]
@robnagler 
It would be nice to have interactive plotting enabled. The old `%matplotlib notebook` option no longer works in Jupyterlab. Per https://github.com/jupyterlab/jupyterlab/issues/2948 It looks like the replacement for this is through: https://github.com/matplotlib/jupyter-matplotlib.

Following the install  procedure for jupyter-matplotlib reproduces an error discussed here for me:

https://stackoverflow.com/questions/50149562/jupyterlab-interactive-plot#comment87317234_50149562

**Comment by ncook882** [comment]
@robnagler this problem was resolved by clearing the corresponding cookies for the jupyter server. I was unable to reproduce this problem on firefox, but will pay attention in the future.

> Upon returning to a Jupyter lab session I received the following error:
> 
> <img alt="screen shot 2018-11-14 at 6 12 26 pm" width="308" src="https://user-images.githubusercontent.com/11053323/48523312-249f4e00-e839-11e8-8962-07f673acf9cd.png">
> 
> The standard 'tree' configuration still works, but lab is unresponsive. @robnagler, this may be related to the unique configuration being used for my server. I've yet to reproduce it on other servers.

**Comment by robnagler** [comment]
I added the jupyter-matplotlib, and it works for me. Please try.

**Comment by cchall** [comment]
My test of jupyter-matplotlib works.
I'll try a more complete test with a Python3 project this evening.

**Comment by robnagler** [comment]
Deployed.

**Comment by bruhwiler** [comment]
Now that jupyter-matplotlib has been added, what is the correct syntax for interactive plotting?

For example, if not 
   %matplotlib notebook
then what...?

**Comment by bruhwiler** [comment]
The answer is 
%matplotlib widget

However, you need the appropriate bits to be pip installed.
I'll create a separate issue for that.
