### ISSUE TITLE
Add SDDS to py3

### ISSUE THREAD

**Issue by robnagler** [radiasoft/container-beamsim-jupyter-base#9]
Likely ICFA-ML tutorial will use Elegant so they may want it in py3.

**Comment by robnagler** [comment]
@j-edelen I added SDDS on py3 as a "good idea", but now I would like to avoid installing. W are currently using the Fedora 27 RPM, which is built for py2. We would have to build from source in order to run on py3. SDDS builds are non-trivial (involves configuring EPICS).  Let me know what you think about only supporting SDDS from Python in py2.

**Comment by j-edelen** [comment]
@robnagler, if anyone uses elegant, then we will probably need sdds. I will inquire about this.

**Comment by robnagler** [comment]
SDDS will be available from the command line. It will also be available in Python 2 notebooks and programs. I just don't know if you are planning to do a lot with SDDS from within a Python 3 notebook or program.

**Comment by robnagler** [comment]
This wasn't needed.
