### ISSUE TITLE
Add julia to jupyter

### ISSUE THREAD

**Issue by j-edelen** [radiasoft/container-beamsim-jupyter-base#95]
Please add julia to jupyter and also enable julia notebooks. This is relatively urgent for the cesar phase 1

**Comment by robnagler** [comment]
Which version?

**Comment by j-edelen** [comment]
1.9.3 please

**Comment by e-carlin** [comment]
@j-edelen this is now on prod. Restart your server to get the update.

**Comment by j-edelen** [comment]
It is working, can you please add the following packages? 

"IJulia"
"Plots"
"Colors"
"ColorSchemes"
"Distributions"
"LaTeXStrings"
"QuadGK"
"CUDA"
"HDF5"
"LazyGrids"
"BenchmarkTools"
"NPZ"
"JLD"
"JLD2"
"FileIO"

**Comment by robnagler** [comment]
You can add the packages, just need to re-add them when you restart your server. Once you decide on which packages are useful to you, we can add them to the build.

**Comment by j-edelen** [comment]
Yes, this is what I am asking.

**Comment by robnagler** [comment]
> Yes, this is what I am asking.

Please clarify: Are you asking to add them to the build, because you are already up and running? How many people are using Julia right now?

I don't see MPI in the list, which seems like it might be useful.

**Comment by j-edelen** [comment]
I am asking these to be added to the build because I know I need these packages for my workflow. Chris and I are currently using Julia. I am dealing with some debugging that from my understanding doesn't involve package management. So I am not fully up and running but getting there. We can defer this until I am fully up and running if you prefer.

**Comment by robnagler** [comment]
Yes, let's defer. The builds take a week, and this won't get in this week, so it would be two weeks. Better to save up updates when there are only two people involved.
